-- DO NOT SUBMIT THAT INTO JUDGE SYSTEM
ALTER TABLE `towns`
CHANGE COLUMN `town_id` `id` INT PRIMARY KEY AUTO_INCREMENT;
-- DO NOT SUBMIT THAT INTO JUDGE SYSTEM

ALTER TABLE `minions`
ADD COLUMN `town_id` INT;

ALTER TABLE `minions`
ADD CONSTRAINT fk_town 
FOREIGN KEY (town_id)
REFERENCES towns(id);